#!/usr/bin/python3

import argparse

import dmedia
from dmedia.gtk.peering import ServerUI
from dmedia.service import get_proxy


parser = argparse.ArgumentParser()
parser.add_argument('--version', action='version', version=dmedia.__version__)
parser.add_argument('peer', help='peer ID')
args = parser.parse_args()


log = dmedia.configure_logging()
try:
    ui = ServerUI(get_proxy(), args.peer)
    ui.run()
except Exception:
    log.exception('Crash in ServerUI.run()')

