#!/usr/bin/env python

# Authors:
#   Jason Gerard DeRose <jderose@novacut.com>
#
# dmedia: distributed media library
# Copyright (C) 2010 Jason Gerard DeRose <jderose@novacut.com>
#
# This file is part of `dmedia`.
#
# `dmedia` is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# `dmedia` is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with `dmedia`.  If not, see <http://www.gnu.org/licenses/>.

"""
dmedia importer DBus service at "org.freedesktop.DMedia.Importer".
"""

import argparse
import json
import time

import dmedia
from dmedia.constants import BUS, IMPORT_BUS


parser = argparse.ArgumentParser(
    description='dmedia importer DBus service @{!r}'.format(IMPORT_BUS),
)
parser.add_argument('--version', action='version', version=dmedia.__version__)
parser.add_argument('--no-gui',
    help='run without NotifyOSD and Application Indicators',
    action='store_true',
    default=False,
)
parser.add_argument('--bus',
    help='DBus bus name; default is %(default)r',
    default=IMPORT_BUS,
)
parser.add_argument('--env',
    help='dmedia environment as JSON serialized string',
    metavar='JSON',
)

args = parser.parse_args()
dmedia.configure_logging('importer')

from dbus.mainloop.glib import DBusGMainLoop
DBusGMainLoop(set_as_default=True)

from gi.repository import GObject
GObject.threads_init()


if args.env:
    env = json.loads(args.env)
else:
    import dbus
    conn = dbus.SessionBus()
    proxy = conn.get_object(BUS, '/')
    env = json.loads(proxy.GetEnv())
if args.no_gui:
    env['no_gui'] = True


from dmedia.gtkui.service import DMedia

mainloop = GObject.MainLoop()
obj = DMedia(env, args.bus, mainloop.quit)
mainloop.run()
