#!/usr/bin/env python

# Authors:
#   David Green <david4dev@gmail.com>
#
# dmedia: distributed media library
# Copyright (C) 2010 Jason Gerard DeRose <jderose@novacut.com>
#
# This file is part of `dmedia`.
#
# `dmedia` is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# `dmedia` is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with `dmedia`.  If not, see <http://www.gnu.org/licenses/>.

from dmedialib.client import Client
import gtk

client = Client()

client.version()

def op(string):
    print string
    return string

client.connect(
    "import_started",
    lambda signal, base: op(
        "%s import started" % base
    )
)
client.connect(
    "import_finished",
    lambda signal, base, stats: op(
        "%s import finished - stats: %s" % (base, str(stats))
    )
)
client.connect(
    "import_progress",
    lambda signal, base, completed, total, info: op(
        "%s import progress %s/%s - info %s" % (base, str(completed), str(total), str(info))
    )
)
client.connect(
    "batch_import_started",
    lambda signal: op(
        "batch import started"
    )
)
client.connect(
    "batch_import_finished",
    lambda signal, stats: op(
        "batch import started - stats: %s" % str(stats)
    )
)

gtk.main()
