#!/usr/bin/env python

# Authors:
#   Jason Gerard DeRose <jderose@novacut.com>
#
# dmedia: distributed media library
# Copyright (C) 2010 Jason Gerard DeRose <jderose@novacut.com>
#
# This file is part of `dmedia`.
#
# `dmedia` is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# `dmedia` is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with `dmedia`.  If not, see <http://www.gnu.org/licenses/>.

import optparse

import dbus
from dbus.mainloop.glib import DBusGMainLoop

DBusGMainLoop(set_as_default=True)

import dmedia
from dmedia.constants import IMPORT_BUS, DBNAME
from dmedia.abstractcouch import get_env


parser = optparse.OptionParser(version=dmedia.__version__)
parser.add_option('--bus',
    default=IMPORT_BUS,
    help='D-Bus bus name; default is {!r}'.format(IMPORT_BUS),
)
parser.add_option('--dbname',
    metavar='DB',
    default=DBNAME,
    help='CouchDB database; default is {!r}'.format(DBNAME),
)
parser.add_option('--no-gui',
    action='store_true',
    default=False,
    help='run without NotifyOSD and Application Indicators',
)


if __name__ == '__main__':
    (options, args) = parser.parse_args()

    dmedia.configure_logging('import-service')

    env = get_env(options.dbname)
    env['bus'] = options.bus
    env['no_gui'] = options.no_gui

    from dmedia.gtkui import service
    from gi.repository import GObject
    mainloop = GObject.MainLoop()
    obj = service.DMedia(env, mainloop.quit)
    mainloop.run()
