#!/usr/bin/env python

# Authors:
#   David Green <david4dev@gmail.com>
#   Jason Gerard DeRose <jderose@novacut.com>
#
# dmedia: distributed media library
# Copyright (C) 2010 Jason Gerard DeRose <jderose@novacut.com>
#
# This file is part of `dmedia`.
#
# `dmedia` is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# `dmedia` is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with `dmedia`.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function

import sys
import optparse
from os import path

import dmedialib
from dmedialib.client import Client
from dmedia_import.firstrun import FirstRunGUI


parser = optparse.OptionParser(
    version=dmedialib.__version__,
    usage='%prog DIRECTORY',
)
parser.add_option('--unset',
    action='store_true',
    default=False,
    help='unset gconf value to repeat first-run behavior',
)
parser.add_option('--quick',
    dest='extract',
    action='store_false',
    default=True,
    help='import without metadata extraction or thumbnail generation',
)


def usage(msg, code=1):
    parser.print_usage()
    print('ERROR: ' + msg)
    sys.exit(code)


if __name__ == '__main__':
    (options, args) = parser.parse_args()
    if len(args) != 1:
        usage('requires single argument DIRECTORY')
    base = path.abspath(args[0])
    if not path.isdir(base):
        usage('not a directory: %r' % base)
    if not FirstRunGUI.run_if_first_run(base, options.unset):
        print('import_canceled')
        sys.exit(2)
    client = Client()
    action = client.start_import(base, options.extract)
    print(action)
    if action != 'started':
        sys.exit(3)
