#!/usr/bin/env python

# Authors:
#   Jason Gerard DeRose <jderose@novacut.com>
#
# dmedia: distributed media library
# Copyright (C) 2010 Jason Gerard DeRose <jderose@novacut.com>
#
# This file is part of `dmedia`.
#
# `dmedia` is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# `dmedia` is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with `dmedia`.  If not, see <http://www.gnu.org/licenses/>.

import optparse
from paste import httpserver
import dmedialib
from dmedialib.ui import WSGIApp


parser = optparse.OptionParser(version=dmedialib.__version__)
parser.add_option('--host',
    help='Listen on address HOST (default=127.0.0.1)',
    default='127.0.0.1',
)
parser.add_option('--port',
    help='Listen on PORT (default=8080)',
    default=8080,
    type='int',
)
(options, args) = parser.parse_args()

app = WSGIApp()
httpserver.serve(app,
    host=options.host,
    port=options.port,
)
