#!/usr/bin/env python

# Authors:
#   David Green <david4dev@gmail.com>
#
# dmedia: distributed media library
# Copyright (C) 2010 Jason Gerard DeRose <jderose@novacut.com>
#
# This file is part of `dmedia`.
#
# `dmedia` is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# `dmedia` is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with `dmedia`.  If not, see <http://www.gnu.org/licenses/>.

from dmedialib.client import Client
import gtk

client = Client()

client.version()

def op(string):
    print string
    return string

client.connect(
    "import_started",
    lambda base: op(
        "%s import started" % base
    )
)
client.connect(
    "import_finished",
    lambda base: op(
        "%s import finished" % base
    )
)
client.connect(
    "import_progress",
    lambda base, completed, total: op(
        "%s import progress %s/%s" % (base, str(completed), str(total))
    )
)

gtk.main()
