#!/usr/bin/env python

# Authors:
#   Jason Gerard DeRose <jderose@novacut.com>
#   David Green <david4dev@gmail.com>
#
# dmedia: distributed media library
# Copyright (C) 2010, 2011 Jason Gerard DeRose <jderose@novacut.com>
#
# This file is part of `dmedia`.
#
# `dmedia` is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# `dmedia` is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with `dmedia`.  If not, see <http://www.gnu.org/licenses/>.


"""
Command line tool for talking to dmedia DBus services.
"""

from __future__ import print_function

import argparse
import json

import dbus

import dmedia
from dmedia.constants import BUS, IFACE


parser = argparse.ArgumentParser(
    description='Execute methods on dmedia DBus services',
)
parser.add_argument('--version', action='version', version=dmedia.__version__)
parser.add_argument('--bus',
    help='DBus bus name; default is %(default)r',
    default=BUS,
)


sub = parser.add_subparsers(
    dest='cmd',
    title='Methods on {}'.format(BUS)
)


# DMedia.Version()
sub.add_parser('Version',
    help='version of running `dmedia-service`',
)


# DMedia.Kill()
sub.add_parser('Kill',
    help='shutdown `dmedia-service`',
)


# DMedia.AddFileStore()
p = sub.add_parser('AddFileStore',
    help='add a new FileStore',
)
p.add_argument('parentdir',
    help="parent directory, like '/home/username'"
)
def AddFileStore(method, args):
    print(method(args.parentdir))
p.set_defaults(func=AddFileStore)


# DMedia.GetDoc()
p = sub.add_parser('GetDoc',
    help='get document from CouchDB by doc_id',
)
p.add_argument('doc_id',
    help='the _id of document',
)
def GetDoc(method, args):
    print(method(args.doc_id))
p.set_defaults(func=GetDoc)


# DMedia.GetFile()
p = sub.add_parser('GetFile',
    help='get full path of file by file_id',
)
p.add_argument('file_id',
    help='the _id of file',
)
def GetFile(method, args):
    print(method(args.file_id))
p.set_defaults(func=GetFile)



def default_func(method, args):
    print(method())

args = parser.parse_args()
func = getattr(args, 'func', default_func)
conn = dbus.SessionBus()
proxy = conn.get_object(args.bus, '/')
method = proxy.get_dbus_method(args.cmd, dbus_interface=IFACE)
func(method, args)
