#!/usr/bin/python

# dmedia: distributed media library
# Copyright (C) 2011 Novacut Inc
#
# This file is part of `dmedia`.
#
# `dmedia` is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# `dmedia` is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with `dmedia`.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors:
#   Jason Gerard DeRose <jderose@novacut.com>

"""
Hacky shim till it's possible to implement DBus servers in PyGI.

Note that because this script must be Python2, it can't import anything from the
`dmedia` package as it will only be installed under Python3.
"""

import argparse
import os
from os import path
from subprocess import Popen
import logging
import time
import sys
import json

import xdg.BaseDirectory
import dbus
import dbus.service
from dbus.mainloop.glib import DBusGMainLoop
from dc3lib.microfiber import Database, NotFound


__version__ = '11.10.0'
BUS = 'org.freedesktop.DMedia'
IFACE = BUS
log = logging.getLogger()
service3 = path.join(path.dirname(path.abspath(__file__)), 'dmedia-service3')
assert path.isfile(service3)

DBusGMainLoop(set_as_default=True)
session = dbus.SessionBus()


def configure_logging():
    format = [
        '%(levelname)s',
        '%(message)s',
    ]
    script = path.abspath(sys.argv[0])
    namespace = path.basename(script)
    cache = path.join(xdg.BaseDirectory.xdg_cache_home, 'dmedia')
    if not path.exists(cache):
        os.makedirs(cache)
    filename = path.join(cache, namespace + '.log')
    if path.exists(filename):
        os.rename(filename, filename + '.previous')
    logging.basicConfig(
        filename=filename,
        filemode='w',
        level=logging.DEBUG,
        format='\t'.join(format),
    )
    logging.info('script: %r', script)
    logging.info('dmedia.__file__: %r', __file__)
    logging.info('dmedia.__version__: %r', __version__)


class DMedia(dbus.service.Object):
    def __init__(self, bus, mainloop):
        self._killed = False
        self._bus = bus
        self._mainloop = mainloop

        log.info('Binding to %r', bus)
        super(DMedia, self).__init__(session, object_path='/')
        self._busname = dbus.service.BusName(bus, session)

        self._dc3 = session.get_object('org.freedesktop.DC3', '/')
        self._machine_id = None
        env = self._get_env()

        log.info('Starting %r', service3)
        self._child = Popen([service3, '--bus', bus])
        db = Database('dmedia', env)
        while True:
            try:
                time.sleep(0.1)
                doc = db.get('_local/dmedia')
                self._machine_id = doc['machine_id']
                log.info('machine_id = %r', self._machine_id)
                break
            except NotFound:
                pass

    def _get_env(self):
        log.info('Calling DC3.GetEnv()')
        env = json.loads(self._dc3.GetEnv())
        env['machine_id'] = self._machine_id
        return env

    @dbus.service.method(IFACE, in_signature='', out_signature='s')
    def Version(self):
        """
        Return dmedia version.
        """
        return __version__

    @dbus.service.method(IFACE, in_signature='', out_signature='')
    def Kill(self):
        """
        Kill the `dmedia-service` process.
        """
        if self._killed:
            return
        self._killed = True
        log.info('Killing dmedia core service on %r', self._bus)
        self.FwdKill()
        self._child.wait()
        self._mainloop.quit()

    @dbus.service.signal(IFACE, signature='')
    def FwdKill(self):
        pass

    @dbus.service.method(IFACE, in_signature='', out_signature='s')
    def GetEnv(self):
        """
        Return dmedia env as JSON string.
        """
        return json.dumps(self._get_env())

    @dbus.service.method(IFACE, in_signature='s', out_signature='')
    def AddFileStore(self, parentdir):
        self.FwdAddFileStore(parentdir)

    @dbus.service.signal(IFACE, signature='s')
    def FwdAddFileStore(self, parentdir):
        pass


parser = argparse.ArgumentParser(
    description='DBus service @{}'.format(BUS),
)
parser.add_argument('--version', action='version', version=__version__)
parser.add_argument('--bus',
    default=BUS,
    help='DBus bus name; default is %(default)r',
)
args = parser.parse_args()
configure_logging()

from gi.repository import GObject
GObject.threads_init()

mainloop = GObject.MainLoop()
dmedia = DMedia(args.bus, mainloop)
mainloop.run()
dmedia.Kill()
