#!/usr/bin/python3

from microfiber import Database, dmedia_env
from dmedia.split import migrate_if_needed
from dmedia.util import get_db


env = dmedia_env()
db = get_db(env, init=True)
print(migrate_if_needed(db))
print(db.get('_local/dmedia'))
    

        
    


