#!/usr/bin/env python

# Authors:
#   Jason Gerard DeRose <jderose@novacut.com>
#
# dmedia: distributed media library
# Copyright (C) 2011 Jason Gerard DeRose <jderose@novacut.com>
#
# This file is part of `dmedia`.
#
# `dmedia` is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# `dmedia` is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with `dmedia`.  If not, see <http://www.gnu.org/licenses/>.

import optparse

parser = optparse.OptionParser()
parser.add_option('--browser',
    action='store_true',
    default=False,
    help='open test in default browser instead of dummy client',
)
parser.add_option('--show',
    action='store_true',
    default=False,
    help='make dummy client open a window instead of running headless',
)
(options, args) = parser.parse_args()

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('WebKit', '3.0')
from gi.repository import Gtk, WebKit

window = Gtk.Window()
window.set_title('test')
window.set_default_size(800, 450)
window.connect('destroy', Gtk.main_quit)

scroll = Gtk.ScrolledWindow()
scroll.set_policy(Gtk.PolicyType.AUTOMATIC, Gtk.PolicyType.AUTOMATIC)
window.add(scroll)

view = WebKit.WebView()
scroll.add(view)

view.load_uri(args[0])

if options.show:
    window.show_all()
Gtk.main()
