#!/usr/bin/python3

import json
from os import path

from microfiber import random_id

import dmedia


def dumps(obj):
    return json.dumps(obj, sort_keys=True, separators=(',', ': '), indent=4)


obj = {
    'library_id': random_id(),
    'env': {'url': 'http://localhost:5984/', 'port': 5984},
}
obj_s = dumps(obj)

f = path.join(dmedia.get_dmedia_dir(), 'library.json')
open(f, 'w').write(obj_s)
print(obj_s)
print('')
print('Written to {}'.format(f))
print('')
print('Copy this file onto removable media, and from there copy it into the')
print('    ~/.local/share/dmedia/')
print('directory on your other computers.')

