#!/usr/bin/python3

import sys
from os import path
from dmedia.util import init_filestore

if len(sys.argv) != 2:
    print('takes exactly one argument PARENTDIR')
    sys.exit(1)

parentdir = path.abspath(sys.argv[1])
try:
    (fs, doc) = init_filestore(parentdir)
    fs.init_dirs()  # Force init_dirs() to make sure layout is correct
except Exception:
    pass
