#!/usr/bin/env python

import sys
import optparse
import os
from os import path
from subprocess import call

python = '/usr/bin/python'
nose = '/usr/bin/nosetests'

parser = optparse.OptionParser(
	usage='usage: %prog [MODULES...]',
)
parser.add_option('--pdb',
	action='store_true',
	default=False,
	help='Drop into debugger on errors',
)
parser.add_option('--pdb-failures',
	action='store_true',
	default=False,
	help='Drop into debugger on failures',
)
parser.add_option('--stop',
	action='store_true',
	default=False,
	help='Stop running tests after the first error or failure',
)
(options, args) = parser.parse_args()

cmd = [python, nose] + args + [
    '-v',
    '--with-doctest',
    '--doctest-tests',
]
if options.pdb:
    cmd.append('--pdb')
if options.pdb_failures:
    cmd.append('--pdb-failures')
if options.stop:
    cmd.append('--stop')

sys.exit(call(cmd))
