#!/usr/bin/env python

# Authors:
#   Jason Gerard DeRose <jderose@jasonderose.org>
#
# media: distributed media library
# Copyright (C) 2010 Jason Gerard DeRose <jderose@jasonderose.org>
#
# This file is part of `media`.
#
# `media` is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# `media` is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with `media`.  If not, see <http://www.gnu.org/licenses/>.


"""
10 - 5111906 - 1306722
100 - 2703458 - 1306722

100 (short id) - 2269282 - 1101922

400 - 1667170 - 1302626
400 (with exif) - 2003042 - 1634402
400 (sep ext) - 1998946 - 1646690

1000 - 1310818 - 1306722
"""


import sys
import os
from os import path
import optparse
import medialib
from medialib.filestore import FileStore
from medialib.metastore import MetaStore
from medialib.extractor import extract

args = sys.argv[1:]

base = args[0]
extensions = frozenset(a.lower() for a in args[1:])


store = FileStore()
db = MetaStore()


buf = []
scanned = 0
added = 0
for (action, filename, key) in store.add_recursive(args[0], extensions):
    key = key[:56]
    scanned += 1
    if action != 'skipped':
        added += 1
        print '  %s %r' % (action, filename)
        meta = dict(
            extract(filename, ('_id', key))
        )
        buf.append(db.new(meta))
    if len(buf) >= 400:
        db.db.put_records_batch(buf)
        buf = []

if buf:
    db.db.put_records_batch(buf)

print 'Added %d files; scanned %d' % (added, scanned)
