#!/usr/bin/python3

import sys
from os import path
from dmedia.core import init_filestore

if len(sys.argv) != 2:
    print('takes exactly one argument PARENTDIR')
    sys.exit(1)

(fs, doc) = init_filestore(sys.argv[1])
fs.init_dirs()  # Force init_dirs() to make sure layout is correct
